const ink = "#08152e";
const muted = "#95a0aa";

export default function Terms() {
  return (
    <main style={{ maxWidth: 720, margin: "0 auto", padding: "80px 24px", color: ink }}>
      <a href="/" style={{ color: muted, textDecoration: "none", fontSize: 14 }}>← Osmo</a>
      <h1 style={{ fontSize: 40, fontWeight: 600, marginTop: 16 }}>Terms of Service</h1>
      <p style={{ color: muted, fontSize: 16, lineHeight: 1.6 }}>
        Last updated: July 2026. These terms govern your use of the Osmo app and service.
        By installing or using Osmo, you agree to them.
      </p>

      <Section title="The service">
        Osmo is a macOS application that connects your messages across platforms, remembers
        the people you talk to, and drafts replies with the help of a language model. Some
        features are free; others require an Osmo Pro subscription.
      </Section>

      <Section title="Your account &amp; eligibility">
        You must be at least 18 years old to use Osmo. You are responsible for the accounts
        and platforms you connect and for keeping your device secure. You agree to connect
        only accounts you own or are authorized to use.
      </Section>

      <Section title="Subscriptions, billing &amp; renewal">
        Osmo Pro is billed monthly or annually through our payment processor. Subscriptions
        renew automatically at the end of each period until cancelled. You can cancel anytime
        from Plan &amp; Billing; you keep Pro until the end of the current period. Prices are
        shown before purchase and may change with notice for future periods. Except where
        required by law, payments are non-refundable.
      </Section>

      <Section title="Free trial">
        If offered, a free trial gives full Pro access for the stated period. Unless you
        cancel before it ends, it converts to a paid subscription at the then-current price.
        Each customer is eligible for one trial.
      </Section>

      <Section title="Acceptable use">
        Osmo helps you communicate clearly and kindly. You agree not to use it to harass,
        deceive, impersonate, or manipulate anyone, to violate any platform&apos;s terms, or
        to break the law. You are responsible for every message you choose to send — Osmo
        drafts, but you approve and send.
      </Section>

      <Section title="Your content &amp; data">
        Your messages stay encrypted on your Mac; we do not store your conversation content
        on our servers. See the <a href="/privacy" style={{ color: "#0a84ff" }}>Privacy
        Policy</a> for details. You retain all rights to your content.
      </Section>

      <Section title="AI-generated suggestions">
        Draft suggestions are generated by a language model and may be inaccurate or
        inappropriate. They are suggestions, not advice. Review everything before sending.
        Osmo is not liable for messages you choose to send.
      </Section>

      <Section title="Disclaimers &amp; liability">
        Osmo is provided &quot;as is,&quot; without warranties of any kind. To the maximum
        extent permitted by law, Osmo and its makers are not liable for indirect, incidental,
        or consequential damages, and total liability is limited to the amount you paid in
        the prior twelve months.
      </Section>

      <Section title="Termination">
        You may stop using Osmo and delete your account at any time from within the app. We
        may suspend or terminate access for violations of these terms. On deletion, your
        server-side records are purged and your local data can be erased from Settings.
      </Section>

      <Section title="Changes &amp; contact">
        We may update these terms; material changes will be surfaced in the app or by email.
        Continued use after an update means you accept it. Questions? Email{" "}
        <a href="mailto:hi@osmo.app" style={{ color: "#0a84ff" }}>hi@osmo.app</a>.
      </Section>

      <p style={{ color: muted, fontSize: 13, marginTop: 40 }}>© 2026 Osmo</p>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginTop: 32 }}>
      <h2 style={{ fontSize: 18, fontWeight: 590, margin: "0 0 8px" }}>{title}</h2>
      <p style={{ color: muted, fontSize: 15, lineHeight: 1.6, margin: 0 }}>{children}</p>
    </section>
  );
}
